# Generated by Django 2.0.5 on 2018-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_url', models.CharField(default='http://localhost:2448/generatereport', max_length=200, verbose_name='Url сервиса получения pdf файла')),
                ('template_name', models.CharField(max_length=200, verbose_name='Имя шаблона')),
                ('file_format', models.CharField(default='pdf', max_length=10, verbose_name='Формат файла')),
                ('report_name', models.CharField(default='report', max_length=200, verbose_name='Наименование отчёта')),
                ('data', models.TextField(verbose_name='Данные для отчёта в формате XML')),
                ('rawData', models.FileField(blank=True, null=True, upload_to='', verbose_name='Pdf файл')),
            ],
            options={
                'verbose_name': 'Данные для получения PDF файла',
                'verbose_name_plural': 'Реестр pdf файлов',
            },
        ),
    ]
