# Generated by Django 2.0.5 on 2018-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='rawData',
            field=models.TextField(blank=True, null=True, verbose_name='Pdf файл'),
        ),
    ]
